name: long_horizon

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    hand_point_cloud:
      shape: [1024, 3]
      type: point_cloud
    object_point_cloud:
      shape: [1024, 3]
      type: point_cloud
    joint_state:
      shape: [22]
      type: low_dim
  joint_action:
    shape: [22]
  contact_map:
    shape: [1024]

env_runner:
  _target_: CordViP.env_runner.robot_runner.RobotRunner
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  task_name: robot

dataset:
  _target_: CordViP.dataset.robot_dataset.RobotDataset
  zarr_path: /home/fqx/CordViP_code/code_release/policy/CordViP/CordViP/data/${task.name}_36.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
  max_train_episodes: null
