name: task_config

image_shape: &image_shape [3, 480, 640]
shape_meta: &shape_meta
  obs:
    img:
      shape: *image_shape
      type: rgb
    joint_state:
      shape: [22]
      type: low_dim
  joint_action:
    shape: [22]

env_runner:
  _target_: BCRNN.env_runner.pusht_image_runner.PushTImageRunner
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  legacy_test: True
  test_start_seed: 100000
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: BCRNN.dataset.robot_image_dataset.RobotImageDataset
  zarr_path: 
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
